org: puneetsharma
app: backensaws
service: aws-node-project
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x

functions:
  getProductById:
    handler: src/handlers/getProductById.getProductById
    events:
      - http:
          path: /products/{productId}
          method: get
          cors: true
  getProductsList:
    handler: src/handlers/getProductsList.getProductsList
    events:
      - http:
          path: /products
          method: get
          cors: true